### ISSUE TITLE
about general logging

### ISSUE THREAD

**Issue by tsingson** [zhu327/pingsix#7]
is there general  logging plugin for routers that not any plugins within ?

**Comment by zhu327** [comment]
1. Plan to implement global plugin configuration by referencing apisix Glocal rule.
https://apisix.apache.org/docs/apisix/terminology/global-rule/

2. The plan refers to the following content to implement the logging plugin.
https://github.com/pandora-web-server/pandora-web-server/tree/main/common-log-module
https://apisix.apache.org/docs/apisix/plugins/file-logger/

If you're interested, you can help take a look; I don't have time to deal with it for now.

**Comment by zhu327** [comment]
I have implemented the global rule, and there is currently no particularly good way for the log plugin, so I won't do it for now.

**Comment by tsingson** [comment]
thanks for comments,    i will take a try.

**Comment by zhu327** [comment]
The project now supports logging to files in a format similar to Nginx logs. I've used an unbounded_channel to convert synchronous logs to asynchronous file writes. I'm unsure of the performance impact of this and will need to evaluate it through benchmarking.
